/*
 * ProWritingAid API V2
 * Official ProWritingAid API Version 2
 *
 * OpenAPI spec version: v2
 * Contact: hello@prowritingaid.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package ProWritingAid.SDK;

import java.util.Objects;
import ProWritingAid.SDK.AnalysisSummaryGraphItem;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * AnalysisSummaryGraph
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-10-15T12:42:14.072+01:00")
public class AnalysisSummaryGraph {
  @SerializedName("Name")
  private String name = null;

  @SerializedName("Items")
  private List<AnalysisSummaryGraphItem> items = null;

  public AnalysisSummaryGraph name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public AnalysisSummaryGraph items(List<AnalysisSummaryGraphItem> items) {
    this.items = items;
    return this;
  }

  public AnalysisSummaryGraph addItemsItem(AnalysisSummaryGraphItem itemsItem) {
    if (this.items == null) {
      this.items = new ArrayList<AnalysisSummaryGraphItem>();
    }
    this.items.add(itemsItem);
    return this;
  }

   /**
   * Get items
   * @return items
  **/
  @ApiModelProperty(value = "")
  public List<AnalysisSummaryGraphItem> getItems() {
    return items;
  }

  public void setItems(List<AnalysisSummaryGraphItem> items) {
    this.items = items;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AnalysisSummaryGraph analysisSummaryGraph = (AnalysisSummaryGraph) o;
    return Objects.equals(this.name, analysisSummaryGraph.name) &&
        Objects.equals(this.items, analysisSummaryGraph.items);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, items);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AnalysisSummaryGraph {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    items: ").append(toIndentedString(items)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

