/*
 * ProWritingAid API V2
 * Official ProWritingAid API Version 2
 *
 * OpenAPI spec version: v2
 * Contact: hello@prowritingaid.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package ProWritingAid.SDK;

import java.util.Objects;
import ProWritingAid.SDK.AnalysisSummary;
import ProWritingAid.SDK.DocTag;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * TextAnalysisResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-10-15T12:42:14.072+01:00")
public class TextAnalysisResponse {
  @SerializedName("Tags")
  private List<DocTag> tags = new ArrayList<DocTag>();

  @SerializedName("WordCount")
  private Integer wordCount = null;

  @SerializedName("Summaries")
  private List<AnalysisSummary> summaries = new ArrayList<AnalysisSummary>();

  public TextAnalysisResponse tags(List<DocTag> tags) {
    this.tags = tags;
    return this;
  }

  public TextAnalysisResponse addTagsItem(DocTag tagsItem) {
    this.tags.add(tagsItem);
    return this;
  }

   /**
   * List of found suggestions
   * @return tags
  **/
  @ApiModelProperty(required = true, value = "List of found suggestions")
  public List<DocTag> getTags() {
    return tags;
  }

  public void setTags(List<DocTag> tags) {
    this.tags = tags;
  }

  public TextAnalysisResponse wordCount(Integer wordCount) {
    this.wordCount = wordCount;
    return this;
  }

   /**
   * Number of processed words
   * @return wordCount
  **/
  @ApiModelProperty(required = true, value = "Number of processed words")
  public Integer getWordCount() {
    return wordCount;
  }

  public void setWordCount(Integer wordCount) {
    this.wordCount = wordCount;
  }

  public TextAnalysisResponse summaries(List<AnalysisSummary> summaries) {
    this.summaries = summaries;
    return this;
  }

  public TextAnalysisResponse addSummariesItem(AnalysisSummary summariesItem) {
    this.summaries.add(summariesItem);
    return this;
  }

   /**
   * 
   * @return summaries
  **/
  @ApiModelProperty(required = true, value = "")
  public List<AnalysisSummary> getSummaries() {
    return summaries;
  }

  public void setSummaries(List<AnalysisSummary> summaries) {
    this.summaries = summaries;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TextAnalysisResponse textAnalysisResponse = (TextAnalysisResponse) o;
    return Objects.equals(this.tags, textAnalysisResponse.tags) &&
        Objects.equals(this.wordCount, textAnalysisResponse.wordCount) &&
        Objects.equals(this.summaries, textAnalysisResponse.summaries);
  }

  @Override
  public int hashCode() {
    return Objects.hash(tags, wordCount, summaries);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TextAnalysisResponse {\n");
    
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("    wordCount: ").append(toIndentedString(wordCount)).append("\n");
    sb.append("    summaries: ").append(toIndentedString(summaries)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

