/*
 * ProWritingAid API V2
 * Official ProWritingAid API Version 2
 *
 * OpenAPI spec version: v2
 * Contact: hello@prowritingaid.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package ProWritingAid.SDK;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * ThesaurusRequest
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-10-15T12:42:14.072+01:00")
public class ThesaurusRequest {
  @SerializedName("Word")
  private String word = null;

  /**
   * the language used
   */
  @JsonAdapter(LanguageEnum.Adapter.class)
  public enum LanguageEnum {
    EN_US("en_US"),
    
    EN_UK("en_UK"),
    
    EN_AU("en_AU"),
    
    EN_CA("en_CA"),
    
    EN("en"),
    
    ES("es");

    private String value;

    LanguageEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static LanguageEnum fromValue(String text) {
      for (LanguageEnum b : LanguageEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<LanguageEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final LanguageEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public LanguageEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return LanguageEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("Language")
  private LanguageEnum language = LanguageEnum.EN;

  public ThesaurusRequest word(String word) {
    this.word = word;
    return this;
  }

   /**
   * the word for the thesaurus call
   * @return word
  **/
  @ApiModelProperty(required = true, value = "the word for the thesaurus call")
  public String getWord() {
    return word;
  }

  public void setWord(String word) {
    this.word = word;
  }

  public ThesaurusRequest language(LanguageEnum language) {
    this.language = language;
    return this;
  }

   /**
   * the language used
   * @return language
  **/
  @ApiModelProperty(required = true, value = "the language used")
  public LanguageEnum getLanguage() {
    return language;
  }

  public void setLanguage(LanguageEnum language) {
    this.language = language;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ThesaurusRequest thesaurusRequest = (ThesaurusRequest) o;
    return Objects.equals(this.word, thesaurusRequest.word) &&
        Objects.equals(this.language, thesaurusRequest.language);
  }

  @Override
  public int hashCode() {
    return Objects.hash(word, language);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ThesaurusRequest {\n");
    
    sb.append("    word: ").append(toIndentedString(word)).append("\n");
    sb.append("    language: ").append(toIndentedString(language)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

