/*
 * ProWritingAid API V2
 * Official ProWritingAid API Version 2
 *
 * OpenAPI spec version: v2
 * Contact: hello@prowritingaid.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * AnalysisSettings
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-08-28T18:23:44.793+01:00")
public class AnalysisSettings {
  @SerializedName("ShortestAverageSentenceLength")
  private Integer shortestAverageSentenceLength = 11;

  @SerializedName("LongestAverageSentenceLength")
  private Integer longestAverageSentenceLength = 18;

  @SerializedName("LongestIndividualSentence")
  private Integer longestIndividualSentence = 30;

  @SerializedName("HighestPassiveIndex")
  private Integer highestPassiveIndex = 25;

  @SerializedName("MaxGlueIndex")
  private Integer maxGlueIndex = 40;

  @SerializedName("MinSentenceVariety")
  private Integer minSentenceVariety = 3;

  @SerializedName("HighestPronounPercentage")
  private Double highestPronounPercentage = 15.0d;

  @SerializedName("LowestPronounPercentage")
  private Double lowestPronounPercentage = 4.0d;

  @SerializedName("HighestAcademicPronounPercentage")
  private Double highestAcademicPronounPercentage = 2.0d;

  @SerializedName("HighestInitialPronounPercentage")
  private Double highestInitialPronounPercentage = 30.0d;

  @SerializedName("LowestInitialPronounPercentage")
  private Double lowestInitialPronounPercentage = 0.0d;

  @SerializedName("LowestWeWeScore")
  private Double lowestWeWeScore = 0.6d;

  @SerializedName("LongestAverageParagraphLength")
  private Double longestAverageParagraphLength = 6.0d;

  public AnalysisSettings shortestAverageSentenceLength(Integer shortestAverageSentenceLength) {
    this.shortestAverageSentenceLength = shortestAverageSentenceLength;
    return this;
  }

   /**
   * Get shortestAverageSentenceLength
   * @return shortestAverageSentenceLength
  **/
  @ApiModelProperty(required = true, value = "")
  public Integer getShortestAverageSentenceLength() {
    return shortestAverageSentenceLength;
  }

  public void setShortestAverageSentenceLength(Integer shortestAverageSentenceLength) {
    this.shortestAverageSentenceLength = shortestAverageSentenceLength;
  }

  public AnalysisSettings longestAverageSentenceLength(Integer longestAverageSentenceLength) {
    this.longestAverageSentenceLength = longestAverageSentenceLength;
    return this;
  }

   /**
   * Get longestAverageSentenceLength
   * @return longestAverageSentenceLength
  **/
  @ApiModelProperty(required = true, value = "")
  public Integer getLongestAverageSentenceLength() {
    return longestAverageSentenceLength;
  }

  public void setLongestAverageSentenceLength(Integer longestAverageSentenceLength) {
    this.longestAverageSentenceLength = longestAverageSentenceLength;
  }

  public AnalysisSettings longestIndividualSentence(Integer longestIndividualSentence) {
    this.longestIndividualSentence = longestIndividualSentence;
    return this;
  }

   /**
   * Get longestIndividualSentence
   * @return longestIndividualSentence
  **/
  @ApiModelProperty(required = true, value = "")
  public Integer getLongestIndividualSentence() {
    return longestIndividualSentence;
  }

  public void setLongestIndividualSentence(Integer longestIndividualSentence) {
    this.longestIndividualSentence = longestIndividualSentence;
  }

  public AnalysisSettings highestPassiveIndex(Integer highestPassiveIndex) {
    this.highestPassiveIndex = highestPassiveIndex;
    return this;
  }

   /**
   * Get highestPassiveIndex
   * @return highestPassiveIndex
  **/
  @ApiModelProperty(required = true, value = "")
  public Integer getHighestPassiveIndex() {
    return highestPassiveIndex;
  }

  public void setHighestPassiveIndex(Integer highestPassiveIndex) {
    this.highestPassiveIndex = highestPassiveIndex;
  }

  public AnalysisSettings maxGlueIndex(Integer maxGlueIndex) {
    this.maxGlueIndex = maxGlueIndex;
    return this;
  }

   /**
   * Get maxGlueIndex
   * @return maxGlueIndex
  **/
  @ApiModelProperty(required = true, value = "")
  public Integer getMaxGlueIndex() {
    return maxGlueIndex;
  }

  public void setMaxGlueIndex(Integer maxGlueIndex) {
    this.maxGlueIndex = maxGlueIndex;
  }

  public AnalysisSettings minSentenceVariety(Integer minSentenceVariety) {
    this.minSentenceVariety = minSentenceVariety;
    return this;
  }

   /**
   * Get minSentenceVariety
   * @return minSentenceVariety
  **/
  @ApiModelProperty(required = true, value = "")
  public Integer getMinSentenceVariety() {
    return minSentenceVariety;
  }

  public void setMinSentenceVariety(Integer minSentenceVariety) {
    this.minSentenceVariety = minSentenceVariety;
  }

  public AnalysisSettings highestPronounPercentage(Double highestPronounPercentage) {
    this.highestPronounPercentage = highestPronounPercentage;
    return this;
  }

   /**
   * Get highestPronounPercentage
   * @return highestPronounPercentage
  **/
  @ApiModelProperty(required = true, value = "")
  public Double getHighestPronounPercentage() {
    return highestPronounPercentage;
  }

  public void setHighestPronounPercentage(Double highestPronounPercentage) {
    this.highestPronounPercentage = highestPronounPercentage;
  }

  public AnalysisSettings lowestPronounPercentage(Double lowestPronounPercentage) {
    this.lowestPronounPercentage = lowestPronounPercentage;
    return this;
  }

   /**
   * Get lowestPronounPercentage
   * @return lowestPronounPercentage
  **/
  @ApiModelProperty(required = true, value = "")
  public Double getLowestPronounPercentage() {
    return lowestPronounPercentage;
  }

  public void setLowestPronounPercentage(Double lowestPronounPercentage) {
    this.lowestPronounPercentage = lowestPronounPercentage;
  }

  public AnalysisSettings highestAcademicPronounPercentage(Double highestAcademicPronounPercentage) {
    this.highestAcademicPronounPercentage = highestAcademicPronounPercentage;
    return this;
  }

   /**
   * Get highestAcademicPronounPercentage
   * @return highestAcademicPronounPercentage
  **/
  @ApiModelProperty(required = true, value = "")
  public Double getHighestAcademicPronounPercentage() {
    return highestAcademicPronounPercentage;
  }

  public void setHighestAcademicPronounPercentage(Double highestAcademicPronounPercentage) {
    this.highestAcademicPronounPercentage = highestAcademicPronounPercentage;
  }

  public AnalysisSettings highestInitialPronounPercentage(Double highestInitialPronounPercentage) {
    this.highestInitialPronounPercentage = highestInitialPronounPercentage;
    return this;
  }

   /**
   * Get highestInitialPronounPercentage
   * @return highestInitialPronounPercentage
  **/
  @ApiModelProperty(required = true, value = "")
  public Double getHighestInitialPronounPercentage() {
    return highestInitialPronounPercentage;
  }

  public void setHighestInitialPronounPercentage(Double highestInitialPronounPercentage) {
    this.highestInitialPronounPercentage = highestInitialPronounPercentage;
  }

  public AnalysisSettings lowestInitialPronounPercentage(Double lowestInitialPronounPercentage) {
    this.lowestInitialPronounPercentage = lowestInitialPronounPercentage;
    return this;
  }

   /**
   * Get lowestInitialPronounPercentage
   * @return lowestInitialPronounPercentage
  **/
  @ApiModelProperty(required = true, value = "")
  public Double getLowestInitialPronounPercentage() {
    return lowestInitialPronounPercentage;
  }

  public void setLowestInitialPronounPercentage(Double lowestInitialPronounPercentage) {
    this.lowestInitialPronounPercentage = lowestInitialPronounPercentage;
  }

  public AnalysisSettings lowestWeWeScore(Double lowestWeWeScore) {
    this.lowestWeWeScore = lowestWeWeScore;
    return this;
  }

   /**
   * Get lowestWeWeScore
   * @return lowestWeWeScore
  **/
  @ApiModelProperty(required = true, value = "")
  public Double getLowestWeWeScore() {
    return lowestWeWeScore;
  }

  public void setLowestWeWeScore(Double lowestWeWeScore) {
    this.lowestWeWeScore = lowestWeWeScore;
  }

  public AnalysisSettings longestAverageParagraphLength(Double longestAverageParagraphLength) {
    this.longestAverageParagraphLength = longestAverageParagraphLength;
    return this;
  }

   /**
   * Get longestAverageParagraphLength
   * @return longestAverageParagraphLength
  **/
  @ApiModelProperty(required = true, value = "")
  public Double getLongestAverageParagraphLength() {
    return longestAverageParagraphLength;
  }

  public void setLongestAverageParagraphLength(Double longestAverageParagraphLength) {
    this.longestAverageParagraphLength = longestAverageParagraphLength;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AnalysisSettings analysisSettings = (AnalysisSettings) o;
    return Objects.equals(this.shortestAverageSentenceLength, analysisSettings.shortestAverageSentenceLength) &&
        Objects.equals(this.longestAverageSentenceLength, analysisSettings.longestAverageSentenceLength) &&
        Objects.equals(this.longestIndividualSentence, analysisSettings.longestIndividualSentence) &&
        Objects.equals(this.highestPassiveIndex, analysisSettings.highestPassiveIndex) &&
        Objects.equals(this.maxGlueIndex, analysisSettings.maxGlueIndex) &&
        Objects.equals(this.minSentenceVariety, analysisSettings.minSentenceVariety) &&
        Objects.equals(this.highestPronounPercentage, analysisSettings.highestPronounPercentage) &&
        Objects.equals(this.lowestPronounPercentage, analysisSettings.lowestPronounPercentage) &&
        Objects.equals(this.highestAcademicPronounPercentage, analysisSettings.highestAcademicPronounPercentage) &&
        Objects.equals(this.highestInitialPronounPercentage, analysisSettings.highestInitialPronounPercentage) &&
        Objects.equals(this.lowestInitialPronounPercentage, analysisSettings.lowestInitialPronounPercentage) &&
        Objects.equals(this.lowestWeWeScore, analysisSettings.lowestWeWeScore) &&
        Objects.equals(this.longestAverageParagraphLength, analysisSettings.longestAverageParagraphLength);
  }

  @Override
  public int hashCode() {
    return Objects.hash(shortestAverageSentenceLength, longestAverageSentenceLength, longestIndividualSentence, highestPassiveIndex, maxGlueIndex, minSentenceVariety, highestPronounPercentage, lowestPronounPercentage, highestAcademicPronounPercentage, highestInitialPronounPercentage, lowestInitialPronounPercentage, lowestWeWeScore, longestAverageParagraphLength);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AnalysisSettings {\n");
    
    sb.append("    shortestAverageSentenceLength: ").append(toIndentedString(shortestAverageSentenceLength)).append("\n");
    sb.append("    longestAverageSentenceLength: ").append(toIndentedString(longestAverageSentenceLength)).append("\n");
    sb.append("    longestIndividualSentence: ").append(toIndentedString(longestIndividualSentence)).append("\n");
    sb.append("    highestPassiveIndex: ").append(toIndentedString(highestPassiveIndex)).append("\n");
    sb.append("    maxGlueIndex: ").append(toIndentedString(maxGlueIndex)).append("\n");
    sb.append("    minSentenceVariety: ").append(toIndentedString(minSentenceVariety)).append("\n");
    sb.append("    highestPronounPercentage: ").append(toIndentedString(highestPronounPercentage)).append("\n");
    sb.append("    lowestPronounPercentage: ").append(toIndentedString(lowestPronounPercentage)).append("\n");
    sb.append("    highestAcademicPronounPercentage: ").append(toIndentedString(highestAcademicPronounPercentage)).append("\n");
    sb.append("    highestInitialPronounPercentage: ").append(toIndentedString(highestInitialPronounPercentage)).append("\n");
    sb.append("    lowestInitialPronounPercentage: ").append(toIndentedString(lowestInitialPronounPercentage)).append("\n");
    sb.append("    lowestWeWeScore: ").append(toIndentedString(lowestWeWeScore)).append("\n");
    sb.append("    longestAverageParagraphLength: ").append(toIndentedString(longestAverageParagraphLength)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

