/*
 * ProWritingAid API V2
 * Official ProWritingAid API Version 2
 *
 * OpenAPI spec version: v2
 * Contact: hello@prowritingaid.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * AnalysisSummarySubItem
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-08-28T18:23:44.793+01:00")
public class AnalysisSummarySubItem {
  @SerializedName("TagIds")
  private List<String> tagIds = null;

  @SerializedName("Text")
  private String text = null;

  @SerializedName("SuggestionCategory")
  private String suggestionCategory = null;

  @SerializedName("SubCategory")
  private String subCategory = null;

  @SerializedName("SearchTerm")
  private String searchTerm = null;

  public AnalysisSummarySubItem tagIds(List<String> tagIds) {
    this.tagIds = tagIds;
    return this;
  }

  public AnalysisSummarySubItem addTagIdsItem(String tagIdsItem) {
    if (this.tagIds == null) {
      this.tagIds = new ArrayList<String>();
    }
    this.tagIds.add(tagIdsItem);
    return this;
  }

   /**
   * Get tagIds
   * @return tagIds
  **/
  @ApiModelProperty(value = "")
  public List<String> getTagIds() {
    return tagIds;
  }

  public void setTagIds(List<String> tagIds) {
    this.tagIds = tagIds;
  }

  public AnalysisSummarySubItem text(String text) {
    this.text = text;
    return this;
  }

   /**
   * Get text
   * @return text
  **/
  @ApiModelProperty(value = "")
  public String getText() {
    return text;
  }

  public void setText(String text) {
    this.text = text;
  }

  public AnalysisSummarySubItem suggestionCategory(String suggestionCategory) {
    this.suggestionCategory = suggestionCategory;
    return this;
  }

   /**
   * Get suggestionCategory
   * @return suggestionCategory
  **/
  @ApiModelProperty(value = "")
  public String getSuggestionCategory() {
    return suggestionCategory;
  }

  public void setSuggestionCategory(String suggestionCategory) {
    this.suggestionCategory = suggestionCategory;
  }

  public AnalysisSummarySubItem subCategory(String subCategory) {
    this.subCategory = subCategory;
    return this;
  }

   /**
   * Get subCategory
   * @return subCategory
  **/
  @ApiModelProperty(value = "")
  public String getSubCategory() {
    return subCategory;
  }

  public void setSubCategory(String subCategory) {
    this.subCategory = subCategory;
  }

  public AnalysisSummarySubItem searchTerm(String searchTerm) {
    this.searchTerm = searchTerm;
    return this;
  }

   /**
   * Get searchTerm
   * @return searchTerm
  **/
  @ApiModelProperty(value = "")
  public String getSearchTerm() {
    return searchTerm;
  }

  public void setSearchTerm(String searchTerm) {
    this.searchTerm = searchTerm;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AnalysisSummarySubItem analysisSummarySubItem = (AnalysisSummarySubItem) o;
    return Objects.equals(this.tagIds, analysisSummarySubItem.tagIds) &&
        Objects.equals(this.text, analysisSummarySubItem.text) &&
        Objects.equals(this.suggestionCategory, analysisSummarySubItem.suggestionCategory) &&
        Objects.equals(this.subCategory, analysisSummarySubItem.subCategory) &&
        Objects.equals(this.searchTerm, analysisSummarySubItem.searchTerm);
  }

  @Override
  public int hashCode() {
    return Objects.hash(tagIds, text, suggestionCategory, subCategory, searchTerm);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AnalysisSummarySubItem {\n");
    
    sb.append("    tagIds: ").append(toIndentedString(tagIds)).append("\n");
    sb.append("    text: ").append(toIndentedString(text)).append("\n");
    sb.append("    suggestionCategory: ").append(toIndentedString(suggestionCategory)).append("\n");
    sb.append("    subCategory: ").append(toIndentedString(subCategory)).append("\n");
    sb.append("    searchTerm: ").append(toIndentedString(searchTerm)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

