/*
 * ProWritingAid API V2
 * Official ProWritingAid API Version 2
 *
 * OpenAPI spec version: v2
 * Contact: hello@prowritingaid.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.ContextualThesaurusResponse;
import java.io.IOException;

/**
 * Asynchronous request
 */
@ApiModel(description = "Asynchronous request")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-08-28T18:23:44.793+01:00")
public class AsyncResponseContextualThesaurusResponse {
  @SerializedName("TaskId")
  private String taskId = null;

  @SerializedName("Result")
  private ContextualThesaurusResponse result = null;

  public AsyncResponseContextualThesaurusResponse taskId(String taskId) {
    this.taskId = taskId;
    return this;
  }

   /**
   * Async task Id. Empty or null if task was processed synchronously
   * @return taskId
  **/
  @ApiModelProperty(value = "Async task Id. Empty or null if task was processed synchronously")
  public String getTaskId() {
    return taskId;
  }

  public void setTaskId(String taskId) {
    this.taskId = taskId;
  }

  public AsyncResponseContextualThesaurusResponse result(ContextualThesaurusResponse result) {
    this.result = result;
    return this;
  }

   /**
   * Actual response
   * @return result
  **/
  @ApiModelProperty(value = "Actual response")
  public ContextualThesaurusResponse getResult() {
    return result;
  }

  public void setResult(ContextualThesaurusResponse result) {
    this.result = result;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AsyncResponseContextualThesaurusResponse asyncResponseContextualThesaurusResponse = (AsyncResponseContextualThesaurusResponse) o;
    return Objects.equals(this.taskId, asyncResponseContextualThesaurusResponse.taskId) &&
        Objects.equals(this.result, asyncResponseContextualThesaurusResponse.result);
  }

  @Override
  public int hashCode() {
    return Objects.hash(taskId, result);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AsyncResponseContextualThesaurusResponse {\n");
    
    sb.append("    taskId: ").append(toIndentedString(taskId)).append("\n");
    sb.append("    result: ").append(toIndentedString(result)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

