/*
 * ProWritingAid API V2
 * Official ProWritingAid API Version 2
 *
 * OpenAPI spec version: v2
 * Contact: hello@prowritingaid.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.AnalysisSummary;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * HtmlAnalysisResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-08-28T18:23:44.793+01:00")
public class HtmlAnalysisResponse {
  @SerializedName("Html")
  private String html = null;

  @SerializedName("WordCount")
  private Integer wordCount = null;

  @SerializedName("Summaries")
  private List<AnalysisSummary> summaries = new ArrayList<AnalysisSummary>();

  public HtmlAnalysisResponse html(String html) {
    this.html = html;
    return this;
  }

   /**
   * Result in form of html. Contains tags with meta-information
   * @return html
  **/
  @ApiModelProperty(required = true, value = "Result in form of html. Contains tags with meta-information")
  public String getHtml() {
    return html;
  }

  public void setHtml(String html) {
    this.html = html;
  }

  public HtmlAnalysisResponse wordCount(Integer wordCount) {
    this.wordCount = wordCount;
    return this;
  }

   /**
   * Number of processed words
   * @return wordCount
  **/
  @ApiModelProperty(required = true, value = "Number of processed words")
  public Integer getWordCount() {
    return wordCount;
  }

  public void setWordCount(Integer wordCount) {
    this.wordCount = wordCount;
  }

  public HtmlAnalysisResponse summaries(List<AnalysisSummary> summaries) {
    this.summaries = summaries;
    return this;
  }

  public HtmlAnalysisResponse addSummariesItem(AnalysisSummary summariesItem) {
    this.summaries.add(summariesItem);
    return this;
  }

   /**
   * 
   * @return summaries
  **/
  @ApiModelProperty(required = true, value = "")
  public List<AnalysisSummary> getSummaries() {
    return summaries;
  }

  public void setSummaries(List<AnalysisSummary> summaries) {
    this.summaries = summaries;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HtmlAnalysisResponse htmlAnalysisResponse = (HtmlAnalysisResponse) o;
    return Objects.equals(this.html, htmlAnalysisResponse.html) &&
        Objects.equals(this.wordCount, htmlAnalysisResponse.wordCount) &&
        Objects.equals(this.summaries, htmlAnalysisResponse.summaries);
  }

  @Override
  public int hashCode() {
    return Objects.hash(html, wordCount, summaries);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class HtmlAnalysisResponse {\n");
    
    sb.append("    html: ").append(toIndentedString(html)).append("\n");
    sb.append("    wordCount: ").append(toIndentedString(wordCount)).append("\n");
    sb.append("    summaries: ").append(toIndentedString(summaries)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

